### ISSUE TITLE
RE-EDIT: student_index_spec.rb

### ISSUE THREAD

**Issue by Ms-Alex** [learn-co-curriculum/rails-restful-index-action-lab#11]
`describe 'Multiple students are shown' do
  it 'on the index page' do
    Student.create!(first_name: "Daenerys", last_name: "Targaryen")
    Student.create!(first_name: "Lindsey", last_name: "Stirling")

    visit "/students"

    expect(page).to have_content(/(?=.*Daenerys)(?=.*Lindsey).*/)
  end`
--------------------
Okay! So changing "expect(page).to have_content(/(?=.*Daenerys)|(?=.*Lindsey).*/)" 
to:  "expect(page).to have_content(/(?=.*Daenerys)(?=.*Targaryen).*/)" 
is Not the answer. I'm sorry. 
What I found though was that that line of code is missing a ' | '; so:
"expect(page).to have_content(/(?=.*Daenerys)|(?=.*Lindsey).*/)".

Sorry. For the mix up. The test passed this way, and it makes more since adding this ' | ' instead of  changing the name. So this way it checks for both names.

-Alex

**Comment by maxcell** [comment]
Howdy @Ms-Alex! I want to thank you for raising this issue. We ended up coming up with a solution that allows you to put any version of a person's first/full name onto the page and have the test pass! Because of your help, we were able to figure out what is the most readable and effective way of getting people to solve this problem. If you come across anything else please feel free to bring it up!
