### ISSUE TITLE
issue passing student_index_spec.rb:18

### ISSUE THREAD

**Issue by DGMarkel** [learn-co-curriculum/rails-restful-index-action-lab#9]
This test will not pass unless student names are displayed as a list in the view.

**Comment by maxcell** [comment]
You're 100% on the mark @DGMarkel! I am going to close this issue since we managed to write a great way of solving this problem with #12. What the test will expect is for you to iterate over all of the students and display at least their first name. It no longer requires it being inside of any HTML elements but at least to have the text being displayed. Thank you for raising this issue. Please be sure to raise anything else you come across!
